### ISSUE TITLE
ConcurrentModificationException is sometimes thrown when cells are added too often

### ISSUE THREAD

**Issue by slemonide** [slemonide/sasuga#41]
```
Exception in thread "Thread-0" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at model.World.tick(World.java:139)
	at model.World.run(World.java:54)
	at java.lang.Thread.run(Thread.java:745)
```

Usually it's thrown when `World.getInstance().add()` is called too often.

**Comment by slemonide** [comment]
Looks like this is fixed now (hopefully).
